export * from './Home/Home';
export * from './Header/Header';
export * from './MoviesList/MoviesList';
export * from './Movie/Movie';
export * from './MovieInfo/MovieInfo';
export * from './NavGenreList/NavGenreList';
export * from './MovieRating/MovieRating';
export * from './DatNigthSwitcher/DayNightSwitcher'
export * from './Footer/Footer';
export * from './PaginationButtons/PaginationButtons';
